# Use generic build mode on Ubuntu
image: Ubuntu
build: off

environment:
  CODECOV_TOKEN: '29ee40f1-1783-4f4e-b0c6-5c330632b39c'

# Install scripts. (runs after repo cloning)
install:
  # install modules
  - nvm use 16
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash)
